---
- name: play03.yaml
  hosts: "P"
  gather_facts: false
  connection: local

  vars:
    cli:
      host: "{{ inventory_hostname}}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      transport: cli

  tasks:
    - name: timestamp_gatter
      local_action: command date "+%Y-%m-%d-%H:%M:%S"
      register: timestamp

    - name: BF 
      ios_command:
        commands:
          - show run
        provider: "{{ cli }}"
      register: output

    - name: save
      copy:
        content: "{{ output.stdout[0] }}"
        dest: "./backup/{{ inventory_hostname }}_{{ timestamp.stdout[0] }}" 
